### ISSUE TITLE
关于文章授权

### ISSUE THREAD

**Issue by LuiYang08** [gongxuanzhang/gongxuanzhang.github.io#1]
尊敬的 gongxuanzhang，你好。我也是用Hexo-Aurora主题博客的[LuiYang](https://luiyang08.github.io/)，我对于你的[博客 - 删除评论区侧边栏](https://gongxuanzhang.github.io/post/aurora%E5%88%A0%E9%99%A4%E8%AF%84%E8%AE%BA%E4%BE%A7%E8%BE%B9%E6%A0%8F)这篇文章很感兴趣，我希望并请求你能同意，我推广转载你的文章，<a href="mailto:206614221@qq.com"  target="_blank">联系邮箱</a>

**Comment by gongxuanzhang** [comment]
@LuiYang08   可以的  请标明出处即可

**Comment by LuiYang08** [comment]
好的，我会注明出处的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年11月25日 13:52
收件人: ***@***.***>
抄送: ***@***.******@***.***>; ***@***.***>
主题: Re: [gongxuanzhang/gongxuanzhang.github.io] 关于文章授权 (Issue #1)


@LuiYang08<https://github.com/LuiYang08> 可以的 请标明出处即可

―
